### PR TITLE
fix: updates readme

### LINKED ISSUE #201: Update readme
Turns out we have to update the readme

### PR DESCRIPTION
**Pull request by blendaf**
fixes #201

### CODE REVIEW

**Comment by blendaf** [comment]
@juliuscc  I've added all the files, but maybe you do the description for some of them? just search for "something' and you'll see what descriptions are missing

**Comment by juliuscc** [comment]
Let's remember to add a title about user evaluations, and to add the new folder to the list of dirs and documents.

**Comment by blendaf** [comment]
> Let's remember to add a title about user evaluations, and to add the new folder to the list of dirs and documents.

done!

**Review by juliuscc — APPROVED** [review]
Perfect! :) Great job all!

**Pull request merged**
