### PR TITLE
feat: adds a call to action on repeat start page

### PR DESCRIPTION
**Pull request by juliuscc**

### CODE REVIEW

**Review by Falcasantos — APPROVED** [review]
this is, like, a **REALLY** good idea, bravo clap clap 10/10

**Comment by juliuscc** [comment]
I have forgotten to make the buttons do anything oops

**Comment by juliuscc** [comment]
Before I upgrade this to a real pr I want the following tasks done:
- Fix onClicks on the buttons
- Figure out if it should be two call to actions or only one
- Can we change the caption to something more fun?
- Can we have some graphic?
- Can we include the user name?

**Comment by juliuscc** [comment]
@adcaelum @blendaf @catarinallens

**Comment by blendaf** [comment]
Fix onClicks on the buttons: is this something you want input from us on or is it just  a todo?
Figure out if it should be two call to actions or only one: I think there should be two, but they should not have the same priority so the design now I think is good, but I would add a smaller call to action underneath that prompts going to community decks. 
Can we change the caption to something more fun?: maybe "huh, no decks yet?" or something similar. It still has to be clear what the issue is i.e no decks.
Can we have some graphic?: I am thinking something with either the french and British/american flag or words
Can we include the user name? Is there a reason to include the user name?

**Comment by juliuscc** [comment]
Blenda suggested a cloud of words as a graphic

**Pull request merged**
